### ISSUE TITLE
[Question]: Help with eufy security add on disconnecting every few seconds and crashing and after update 2022.8

### ISSUE THREAD

**Issue by sbeukers** [bropat/eufy-security-ws#130]
### Version

0.9.4

### Node version

?

### Operating System type

Docker

### Operating system version

HASSOS

### Describe the bug

Hi,
 
Can someone please help me with the following problem?

Off course I tried all the obvious:
rebooting
reinstalling the add on
ping is steady
The unit is connected with a wire.

The addon crasches since 2022.8
I don’t know for sure if the update to 2022.8 is related.
The system works for a while (form a few hours to a few days but never more than 2 days)
The system was rock solid before

I’ve enabled watchdog.

LOG
2022-08-22 10:50:45.268 INFO Eufy Security server listening on host 0.0.0.0, port 3000
2022-08-22 10:50:55.430 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 12050
2022-08-22 10:50:55.549 INFO Push notification connection successfully established
2022-08-22 10:51:03.441 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:51:08.485 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 14370
2022-08-22 10:51:16.583 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:51:21.630 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 29019
2022-08-22 10:51:29.654 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:51:34.700 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 21930
2022-08-22 10:51:42.743 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:51:47.780 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 24872
2022-08-22 10:51:55.847 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:52:00.883 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 17407
2022-08-22 10:52:08.891 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:52:13.932 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 24746
2022-08-22 10:52:21.975 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:52:27.009 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 18056
2022-08-22 10:52:35.083 INFO Disconnected from station T8010Pxxxxxxxx
2022-08-22 10:52:40.115 INFO Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 25532
undefined:1
SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at /usr/src/app/node_modules/eufy-security-client/build/push/client.js:207:38
at Array.forEach ()
at PushClient.convertPayloadMessage (/usr/src/app/node_modules/eufy-security-client/build/push/client.js:205:17)
at PushClient.handleParsedMessage (/usr/src/app/node_modules/eufy-security-client/build/push/client.js:154:43)
at PushClientParser. (/usr/src/app/node_modules/eufy-security-client/build/push/client.js:56:63)
at PushClientParser.emit (node:events:527:28)
at PushClientParser.onGotMessageBytes (/usr/src/app/node_modules/eufy-security-client/build/push/parser.js:137:14)
at PushClientParser.handleFullMessage (/usr/src/app/node_modules/eufy-security-client/build/push/parser.js:66:22)
at PushClientParser.waitForData (/usr/src/app/node_modules/eufy-security-client/build/push/parser.js:51:18)

Virtual Machine (HyperV) (6 core, 6GB, SSD)
Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.5
Frontend-versie: 20220802.0 - latest

HomeBase 2 version 3.1.9.0h
subsystem 1.3.0.9

Can you please help me with this problem?

It seems like it is constantly disconnecting
I also rebooted the HomeBase

And please let me know if you need anything else.

Best Regards,

Sjoerd Beukers

### To reproduce

see text

### Screenshots & Logfiles

2022-08-24 18:57:13.324  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 28875 
2022-08-24 18:57:21.485  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:57:26.525  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 17360 
2022-08-24 18:57:34.661  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:57:39.716  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 29724 
2022-08-24 18:57:47.885  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:57:49.003  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 20934 
2022-08-24 18:57:57.189  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:58:02.310  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 11840 
2022-08-24 18:58:10.477  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:58:15.520  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 23455 
2022-08-24 18:58:23.661  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:58:28.718  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 20333 
2022-08-24 18:58:36.777  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:58:41.814  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 16923 
2022-08-24 18:58:49.901  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:58:54.944  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 22791 
2022-08-24 18:59:03.061  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:59:08.117  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 29678 
2022-08-24 18:59:16.197  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:59:21.238  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 12409 
2022-08-24 18:59:29.329  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:59:34.372  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 27173 
2022-08-24 18:59:42.477  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 18:59:47.521  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 25682 
2022-08-24 18:59:55.629  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:00:00.671  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 27392 
2022-08-24 19:00:08.777  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:00:13.809  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 19697 
2022-08-24 19:00:21.929  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:00:26.974  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 20310 
2022-08-24 19:00:35.105  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:00:40.144  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 27703 
2022-08-24 19:00:48.189  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:00:53.235  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 27496 
2022-08-24 19:01:01.337  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:01:06.397  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 20339 
2022-08-24 19:01:14.493  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:01:19.533  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 13436 
2022-08-24 19:01:27.670  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:01:32.717  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 15346 
2022-08-24 19:01:40.805  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:01:45.853  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 20064 
2022-08-24 19:01:53.969  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:01:59.019  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 26956 
2022-08-24 19:02:07.110  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:02:12.165  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 21275 
2022-08-24 19:02:20.301  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:02:25.345  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 18720 
2022-08-24 19:02:33.474  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:02:38.636  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 25958 
2022-08-24 19:02:46.897  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:02:51.947  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 12049 
2022-08-24 19:03:00.026  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:03:05.066  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 24008 
2022-08-24 19:03:06.651  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:03:11.690  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 19862 
2022-08-24 19:03:19.846  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:03:24.917  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 16388 
2022-08-24 19:03:33.022  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:03:38.062  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 19977 
2022-08-24 19:03:46.222  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:03:51.263  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 28302 
2022-08-24 19:03:59.382  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:04:04.420  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 23386 
2022-08-24 19:04:12.530  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:04:17.573  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 20591 
2022-08-24 19:04:25.686  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:04:30.725  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 18312 
2022-08-24 19:04:38.846  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:04:43.886  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 18980 
2022-08-24 19:04:52.082  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:04:57.129  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 20389 
2022-08-24 19:05:05.190  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:05:10.225  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 14650 
2022-08-24 19:05:18.410  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:05:23.450  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 16408 
2022-08-24 19:05:31.626  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:05:36.664  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 18290 
2022-08-24 19:05:44.774  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:05:49.810  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 18402 
2022-08-24 19:05:57.926  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:06:02.996  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 17981 
2022-08-24 19:06:11.128  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:06:16.172  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 16692 
2022-08-24 19:06:24.290  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:06:29.332  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 11623 
2022-08-24 19:06:37.482  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:06:42.522  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 15326 
2022-08-24 19:06:50.644  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:06:55.684  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 21260 
2022-08-24 19:07:03.775  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:07:23.821  WARN Station T8010Pxxxxxxx - Tried all hosts, no connection could be established 
2022-08-24 19:07:23.822  INFO  Timeout connecting to station T8010Pxxxxxxx 
2022-08-24 19:07:33.853  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 17558 
2022-08-24 19:07:41.985  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:07:47.028  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 15693 
2022-08-24 19:07:55.185  INFO  Disconnected from station T8010Pxxxxxxx 
2022-08-24 19:08:00.255  INFO  Connected to station T8010Pxxxxxxx on host 192.168.0.xx and port 10288 
2022-08-24 19:08:08.362  INFO  Disconnected from station T8010Pxxxxxxx 

### Additional context

fuatakgun asked me to report it here.
I hope i put this in the right section.
If not sorry!

**Comment by bropat** [comment]
@sbeukers 

I think it is related to [this issue](https://github.com/bropat/eufy-security-client/issues/185).

**Comment by sbeukers** [comment]
> @sbeukers
> 
> I think it is related to [this issue](https://github.com/bropat/eufy-security-client/issues/185), as you stated this above:
> 
> > Virtual Machine (HyperV)
Hi @bropat,

Thanks for the quick reply!

I can't prove or disprove that it is a HyperV thing.
But what I do know for sure is that 2 weeks ago it was rocksolid.
I use the integration for almost a year without any hassle.
Including streaming from the doorbell etc.
No disconnecting every few seconds.

I will try to move the disk to another platform for testing purposes.

The system is quite large
But my hardware is more than capeble.

**Comment by Electr1fying** [comment]
Important addition. I'm using the Homebridge Eufy Plugin, which also uses (a part of) Bropat's Security Client, and since a few days i've had a lot of frequent disconnects (red light on Homebase).

Trying to reset the Homebase results in the message that the Homebase is not connected to the internet, while the live-view is working perfectly fine over a cellular connection at the same time.

I'm also on Homebase firmware 3.1.9.0h and i've read reports on the Eufy forum, where other people reported connection issues with this firmware. Therefore i think this issue is Firmware related and not (strictly) related to any Home Automation plugins.

**Comment by bropat** [comment]
I have now set up a Debian VM on Hyper-V using the default switch and I have noticed that the keepalive UDP packets from the P2P protocol are lost, causing the connection to be terminated by the station after a few seconds.
In the network trace of the VM all packets are present and when I check with Wireshark on the vEthernet (default switch) the UDP keepalive answers do not arrive, the rest does.

**Comment by bropat** [comment]
The solution to this problem is to change the network card of the eufy-security VM to legacy.

You can follow this guide:

1. Remove problematic network card from the VM running eufy-sercurity:
    * Open Hyper-V Manager. Click Start, point to Administrative Tools, and then click Hyper-V Manager.
    * In the results pane, under Virtual Machines, find the virtual machine that you want to configure. The state of the virtual machine should be listed as Off. If it is not, right-click the virtual machine and then click Shut Down.
    * In the Action pane, under the virtual machine name, click Settings.
    * In the navigation pane, click the name of the network adapter.
    * On the Network Adapter page, click Remove.
    * click Apply and continue with next step
2. Add legacy network adapter to the eufy-security VM:
    * In the Settings dialog box, in the navigation pane, click Add Hardware.
    * On the Add Hardware page, select Legacy Network Adapter.
    * Click Add. The Network Adapter page appears.
    * Under Network, select the virtual network you want to connect to. Will probably be default switch.
    * Click OK.
3. Start the VM and try again ;)

**Comment by bropat** [comment]
@sbeukers @Electr1fying 

Please try the above solution and let me know ;)

**Comment by sbeukers** [comment]
Hi @bropat ,

Thanks again for the quick solution.

I can not chose Legacy network adapter because HA starts from gen2 VM.

> This is the instruction on the HA site:
> Create a new virtual machine
> Select “Generation 2”
> Select “Connection -> “Your Virtual Switch that is bridged”
> Select “Use an existing virtual hard disk” and select the VHDX file from above

I tried to make a new machine as gen1 add the disk (without EFI) but HA won't start.
Then i could chose Legacy network adapter.

I will try to make it work somehow. If anyone has an id on how to make this work please let me know

**Comment by bropat** [comment]
@sbeukers @Electr1fying 

With Gen 2 VMs this fixes also the issue:

`ethtool --offload eth0 rx off tx off`

**Comment by Electr1fying** [comment]
Hi @bropat!

I'm not using any Virtual Machine. I just thought i would chime in since i noted @sbeukers also had Firmware 3.1.9.0h running on his/her Homebase.

**Comment by sbeukers** [comment]
> @sbeukers @Electr1fying
> 
> With Gen 2 VMs this fixes also the issue:
> 
> `ethtool --offload eth0 rx off tx off`

Hi @bropat,

First of all thank you again for all the help.

Call me stupid but if I try to put this in the terminal I get:
bash: ethtool: command not found
I also looked in \usr\bin and \usr\sbin

I use HASOS. So not a full Linux distro.

**Comment by bropat** [comment]
@sbeukers 

Try first following command (untested!):

`apk add ethtool`

Note: After a reboot the modification is lost (install of ethtool and ethtool setting).

**Comment by sbeukers** [comment]
@bropat 
Just for testing purposes it's ok that it is lost after reboot. 
But I can't even get that to work

```
[core-ssh ~]$ ethtool --offload eth0 rx off tx off
netlink error: Operation not permitted
```
```
[core-ssh ~]$ sudo
bash: sudo: command not found
```

**Comment by bropat** [comment]
@sbeukers 

With the following command you should at least see the current configuration:

`ethtool -k eth0`

As I am not a Home Assistant user myself, I can't help you at the moment.
I first have to set up a test environment with HassOS under Hyper-V, etc.

**Comment by bropat** [comment]
@sbeukers 

Execute also this command: 

`whoami`

I think you are not root and therefore do not have the necessary rights to change the above settings.
I found [this documentation] (https://developers.home-assistant.io/docs/operating-system/debugging/) on how to access HassOS with root.

**Comment by sbeukers** [comment]
@bropat 
```
[core-ssh ~]$ whoami
root
```
Correct me if I am wrong. A root user should get # not $
su gives me the same prompt sudo dosn't work

Thanks for the help so far!

```
[core-ssh ~]$ ethtool -k eth0
Features for eth0:
rx-checksumming: on[core-ssh ~]$ ethtool -k eth0
Features for eth0:
rx-checksumming: on
tx-checksumming: on
        tx-checksum-ipv4: off [fixed]
        tx-checksum-ip-generic: on
        tx-checksum-ipv6: off [fixed]
        tx-checksum-fcoe-crc: off [fixed]
        tx-checksum-sctp: on
scatter-gather: on
        tx-scatter-gather: on
        tx-scatter-gather-fraglist: on
tcp-segmentation-offload: on
        tx-tcp-segmentation: on
        tx-tcp-ecn-segmentation: on
        tx-tcp-mangleid-segmentation: on
        tx-tcp6-segmentation: on
generic-segmentation-offload: on
generic-receive-offload: off
large-receive-offload: off [fixed]
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on
rx-vlan-filter: off [fixed]
vlan-challenged: off [fixed]
tx-lockless: on [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: on
tx-gre-csum-segmentation: on
tx-ipxip4-segmentation: on
tx-ipxip6-segmentation: on
tx-udp_tnl-segmentation: on
tx-udp_tnl-csum-segmentation: on
tx-gso-partial: off [fixed]
tx-tunnel-remcsum-segmentation: off [fixed]
tx-sctp-segmentation: on
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: on
tx-gso-list: on
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: on
rx-vlan-stag-hw-parse: on
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]
tls-hw-tx-offload: off [fixed]
tls-hw-rx-offload: off [fixed]
rx-gro-hw: off [fixed]
tls-hw-record: off [fixed]
rx-gro-list: off
macsec-hw-offload: off [fixed]
rx-udp-gro-forwarding: off
hsr-tag-ins-offload: off [fixed]
hsr-tag-rm-offload: off [fixed]
hsr-fwd-offload: off [fixed]
hsr-dup-offload: off [fixed]

tx-checksumming: on
        tx-checksum-ipv4: off [fixed]
        tx-checksum-ip-generic: on
        tx-checksum-ipv6: off [fixed]
        tx-checksum-fcoe-crc: off [fixed]
        tx-checksum-sctp: on
scatter-gather: on
        tx-scatter-gather: on
        tx-scatter-gather-fraglist: on
tcp-segmentation-offload: on
        tx-tcp-segmentation: on
        tx-tcp-ecn-segmentation: on
        tx-tcp-mangleid-segmentation: on
        tx-tcp6-segmentation: on
generic-segmentation-offload: on
generic-receive-offload: off
large-receive-offload: off [fixed]
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on
rx-vlan-filter: off [fixed]
vlan-challenged: off [fixed]
tx-lockless: on [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: on
tx-gre-csum-segmentation: on
tx-ipxip4-segmentation: on
tx-ipxip6-segmentation: on
tx-udp_tnl-segmentation: on
tx-udp_tnl-csum-segmentation: on
tx-gso-partial: off [fixed]
tx-tunnel-remcsum-segmentation: off [fixed]
tx-sctp-segmentation: on
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: on
tx-gso-list: on
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: on
rx-vlan-stag-hw-parse: on
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]
tls-hw-tx-offload: off [fixed]
tls-hw-rx-offload: off [fixed]
rx-gro-hw: off [fixed]
tls-hw-record: off [fixed]
rx-gro-list: off
macsec-hw-offload: off [fixed]
rx-udp-gro-forwarding: off
hsr-tag-ins-offload: off [fixed]
hsr-tag-rm-offload: off [fixed]
hsr-fwd-offload: off [fixed]
hsr-dup-offload: off [fixed]

```

**Comment by sbeukers** [comment]
@bropat 

Can I edit something here?
https://www.home-assistant.io/more-info/unsupported/network_manager/

**Comment by bropat** [comment]
@sbeukers 

I think it is not possible with HassOS, because it's based on buildroot (https://github.com/home-assistant/operating-system) and there ethtool is not included.

So in your case I see only 1 solution if you want to stay with HassOS and that is not to use Hyper-V...

**Comment by sbeukers** [comment]
@bropat well I am not giving up yet. 
as for now the integration is not usable for me anymore.

and I use it very intensively.

I use it to block the roll-shutters when the door is open.
And to activate and deactivate the alarm when we are not home.

And it was working without problems whatsover for months.

So if anyone has any idea please let me know!
One big benifit of Hyper-V is that a snapshot is quickly made so testing is no problem

Thanks for all the great work! I realy appreciate it!

**Comment by sbeukers** [comment]
Is there any way to do it with `nmcli`?

**Comment by bropat** [comment]
@sbeukers 

Try this:

`nmcli con modify "Supervisor eth0" ethtool.feature-rx off ethtool.feature-tx off`

**Comment by sbeukers** [comment]
> @sbeukers
> 
> Try this:
> 
> `nmcli con modify "Supervisor eth0" ethtool.feature-rx off ethtool.feature-tx off`
> 
> This configuration is bootstable, but I don't know if it works if the ethtool is missing in the distro...
@bropat 

I tried it directly on the host. It didn't complain but it didn't do anything either.
Can I install ethtool directly on the host somehow?

**Comment by sbeukers** [comment]
@bropat 
`nmcli con modify "Supervisor eth0" ethtool.feature-rx off ethtool.feature-tx off`
After this I rebooted the host and it worked!!!!

@bropat Thank you so much you are a wizzard!

**Comment by bropat** [comment]
Thank you very much for the donation ;)

**Comment by sominaik** [comment]
Hi @bropat @sbeukers 
I am stuck at one point .. pls help
I have Alpine linux distro ,, installed the networkmanager but for nmcli it keeps on saying 'command not found' .. pls help
Also if i try ethtool, it says netlink error

**Comment by vaderag** [comment]
I think I have this same issue maybe (see bug I logged before putting two and two together) 

I'm unclear where these changes could or should be made in HassOS - is it in the addon or integration or configuration.yaml or somewhere else?
