### ISSUE TITLE
[Bug]: Container keeps crashing

### ISSUE THREAD

**Issue by stefan-dascalescu** [bropat/eufy-security-ws#147]
### Version

0.9.4

### Node version

v16.16.0

### Operating System type

Docker

### Operating system version

 20.10.18

### Describe the bug

I have an automation in HomeAssistant to switch cameras to AWAY when the homebase gets switched to away and this happens quite frequently where the container just dies.

I am running a docker in unraid.

### To reproduce

1. Create automation to switch S40 camera to away when homebase is switched to away
2. switch it to away
3. container dies and switch does not happen

### Screenshots & Logfiles

2022-11-10 07:22:25.848  INFO  Alarm mode for station T8010P2322045A57 changed to: AWAY 
/usr/src/app/node_modules/eufy-security-client/build/http/station.js:528
            const securitySettingsData = this.getPropertyValue(propertyName).toString();
                                                                            ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at Station.getArmDelay (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:528:77)
    at Station.onAlarmMode (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:501:31)
    at P2PClientProtocol.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:33:57)
    at P2PClientProtocol.emit (node:events:527:28)
    at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1185:22)
    at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:899:18)
    at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:891:26)
    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:718:26)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:76:56)
    at Socket.emit (node:events:527:28)

**Comment by bropat** [comment]
Already fixed in latest version.
