### ISSUE TITLE
[Bug]: Invalid passport profile response

### ISSUE THREAD

**Issue by droath** [bropat/eufy-security-ws#166]
### Version

1.2.0

### Node version

latest

### Operating System type

Docker

### Operating system version

16-alpine

### Describe the bug

I get the following error showing up in the events log.

```{
    "type": "event",
    "event": {
        "source": "driver",
        "event": "connectionError",
        "error": {
            "stack": "ApiInvalidResponseError: Invalid passport profile response\n    at HTTPApi.login (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:340:51)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async EufySecurity.connect (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:643:9)\n    at async Function.handle (/usr/src/app/dist/lib/driver/message_handler.js:73:25)\n    at async Client.receiveMessage (/usr/src/app/dist/lib/server.js:93:62)",
            "message": "Invalid passport profile response",
            "name": "ApiInvalidResponseError"
        }
    }
}
```

### To reproduce

1. Connect to WS server.
2. Send "start_listening" command. 
3. The error described in the description will be thrown.

**Comment by Firaslaw** [comment]
في الأحد، ١٨ كانون الأول ٢٠٢٢ ٨:١١ ص Travis Tomka ***@***.***>
كتب:

**Comment by martijnpoppen** [comment]
See https://github.com/bropat/eufy-security-client/pull/282
