### ISSUE TITLE
I can no longer get the cameras to show in HA.

### ISSUE THREAD

**Issue by MilesAheadToo** [bropat/eufy-security-ws#183]
### Version

Home Assistant 2023.1.4

### Node version

Uefy 6.2.0

### Operating System type

Other

### Operating system version

Generic x86-64

### Describe the bug

I have 4 Eufy SoloCam and 1 doorbell with a HomeBase. I used to be able to view the cameras then I bought the doorbell. Since I installed the doorbell I have not been able to see any of the cameras. That might just be a coincidence.  I can see everything in the Eufy app, but nothing is showing up in HA.

This is an error log generated that appears to be pointing to a security issue.

`Logger: custom_components.eufy_security
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:86
Integration: Eufy Security (documentation, issues)
First occurred: 15:07:41 (18 occurrences)
Last logged: 17:07:41

Unexpected error fetching eufy_security data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eufy_security/coordinator.py", line 85, in _update_local
    await self._api.poll_refresh()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 160, in poll_refresh
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.poll_refresh))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 343, in _send_message_get_response
    await self.send_message(message.content)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 352, in send_message
    await self._client.send_message(json.dumps(message))
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 86, in send_message
    raise WebSocketConnectionError()
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError
`

### To reproduce

Not sure that I can reproduce it because it is persistent.

### Screenshots & Logfiles

Error log 1
`This error originated from a custom integration.

Logger: custom_components.eufy_security.eufy_security_api
Source: custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py:107
Integration: Eufy Security (documentation, issues)
First occurred: 14:17:01 (1 occurrences)
Last logged: 14:17:01

Exception [Errno 32] Broken pipe - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py", line 103, in setup client_socket.sendall(byte array(self.camera.video_queue.get())) BrokenPipeError: [Errno 32] Broken pipe`

Error log 2

`Logger: custom_components.eufy_security
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:86
Integration: Eufy Security (documentation, issues)
First occurred: 15:07:41 (18 occurrences)
Last logged: 17:07:41

Unexpected error fetching eufy_security data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eufy_security/coordinator.py", line 85, in _update_local
    await self._api.poll_refresh()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 160, in poll_refresh
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.poll_refresh))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 343, in _send_message_get_response
    await self.send_message(message.content)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 352, in send_message
    await self._client.send_message(json.dumps(message))
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 86, in send_message
    raise WebSocketConnectionError()
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError
`

Error log 3

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/eufy_security/eufy_security_api/api_client.py:345
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:36:06 (3 occurrences)
Last logged: 16:39:06

[140077551900592] {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.ddd5bb257ea348279466f867a3b2eeed', 'errorCode': 'device_livestream_already_running'}
[140077551900592] {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.23cc18a52269473f9b2a0ee0512a2db2', 'errorCode': 'device_livestream_already_running'}
[140078133085808] {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.c657ba020c3f42ddad32feae4915a642', 'errorCode': 'device_livestream_already_running'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/eufy_security/camera.py", line 210, in async_turn_on
    await self._start_livestream()
  File "/config/custom_components/eufy_security/camera.py", line 175, in _start_livestream
    if await self.product.start_livestream() is False:
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 143, in start_livestream
    await self.api.start_livestream(self.product_type, self.serial_no)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 226, in start_livestream
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_livestream, serial_no=serial_no))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 345, in _send_message_get_response
    return await future
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.ddd5bb257ea348279466f867a3b2eeed', 'errorCode': 'device_livestream_already_running'}

**Comment by fuatakgun** [comment]
This is not a relevant repository for the issue, all logs are about eufy_security integration.

**Comment by MilesAheadAlso** [comment]
Apologies
