### ISSUE TITLE
[Bug]: T8900 on HomeBase3 error on open/close events

### ISSUE THREAD

**Issue by Actesis** [bropat/eufy-security-ws#192]
### Version

1.3.0

### Node version

unsure, HAOS 9.5, Core 2023.2.1

### Operating System type

Linux

### Operating system version

HAOS 9.5

### Describe the bug

Every time my T8900 sensor is opened or closed, I get the following error.  Connected to HomeBase3.

`2023-01-29 03:55:56.986  ERROR Station T8030P1322420A34 - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1450:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1043:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1031:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:868:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1732:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":1}}\x00'
}`

### To reproduce

Happens every time T8900 sensor is opened or closed.

### Screenshots & Logfiles

`2023-01-29 03:55:56.986  ERROR Station T8030P1322420A34 - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1450:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1043:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1031:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:868:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1732:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":1}}\x00'
}`

### Additional context

Was testing on a VM install but then fully rebuilt on bare metal with latest HAOS and I still get the error.  I've seen others with the same error, possibly with different devices, all appear to be connected to HomeBase3.

**Comment by BalanceBreaker** [comment]
Got the same problem but I am not using a HomeBase 3 but a HomeBase2 instead.

**Comment by fliespl** [comment]
Same on my end wiem homebase2 on firmware :3.2.6.7

**Comment by bropat** [comment]
This is a bug that will be fixed in the next version.

**Comment by bropat** [comment]
Fixed in release `1.3.1` .

**Comment by KillaDreams** [comment]
Still broken for me

**Comment by KillaDreams** [comment]
> Fixed in release `1.3.1` .

Still broken
