### ISSUE TITLE
[Bug]: Installation failed

### ISSUE THREAD

**Issue by raphael2711** [bropat/eufy-security-ws#214]
### Version

1.5.1

### Node version

?

### Operating System type

Linux

### Operating system version

Linux

### Describe the bug

Just installed 1.5.1 and still get the same error in the logs:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/product.py:40
Integration: Eufy Security (documentation, issues)
First occurred: 20:09:55 (2 occurrences)
Last logged: 20:10:19

Error setting up entry Eufy Security for eufy_security
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/eufy_security/init.py", line 50, in async_setup_entry
await coordinator.initialize()
File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
await self._api.connect()
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
await self._set_products()
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 104, in _set_products
self._devices = await self._get_products(ProductType.device, result[MessageField.STATE.value]["devices"])
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 124, in _get_products
product = Device(self, serial_no, properties, metadata, commands)
File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 130, in init
super().init(api, ProductType.device, serial_no, properties, metadata, commands)
File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 33, in init
self._set_properties(properties)
File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 40, in _set_properties
self.name = properties[MessageField.NAME.value]
KeyError: 'name'

### To reproduce

Try to install

**Comment by bropat** [comment]
wrong repo
