### ISSUE TITLE
[Feature request]: S340 Camera Support

### ISSUE THREAD

**Issue by same2you** [bropat/eufy-security-ws#275]
### Describe the solution you'd like

Would love support for the S340 Cameras

**Comment by VincePimentel** [comment]
I second this!

**Comment by Golgautier** [comment]
Me too !

**Comment by wolfjank** [comment]
i fully agree!

**Comment by johannes281** [comment]
+1

**Comment by Beejeedeb** [comment]
Yes please

**Comment by GingerLoaf** [comment]
Just upgraded eufy-security-ws to version 1.8.0 and tried using my S340. No success. I am trying to use it without a station (as standalone) and all I am able to see is the debug entities and nothing else. The logs are showing that it is failing at some kind of gateway api.

2023-12-27 22:17:31.005  DEBUG [undefined.<anonymous>] Handle DATA CONTROL - CMD_GATEWAYINFO - set encryption level 1 (fallback) 
{
  error: {
    cause: undefined,
    message: 'Error: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key',
    context: undefined,
    stacktrace: 'Error: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key\n' +
      '    at module.exports.NodeRSA.$$decryptKey (/usr/src/app/node_modules/node-rsa/src/NodeRSA.js:301:19)\n' +
      '    at module.exports.NodeRSA.decrypt (/usr/src/app/node_modules/node-rsa/src/NodeRSA.js:249:21)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:2002:47\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
  },
  stationSN: 'T8170T1023411951',
  message: {
    seqNo: 0,
    channel: 255,
    commandType: 'CMD_GATEWAYINFO',
    signCode: 1,
    type: 0,
    dataType: 'CONTROL',
    data: 'REDACTED'
  },
  key: 'REDACTED'
}

I would really love to use this camera with my HomeAssistant installation if possible

**Comment by same2you** [comment]
> Just upgraded eufy-security-ws to version 1.8.0 and tried using my S340. No success. I am trying to use it without a station (as standalone) and all I am able to see is the debug entities and nothing else. The logs are showing that it is failing at some kind of gateway api.
> 
> 2023-12-27 22:17:31.005 DEBUG [undefined.] Handle DATA CONTROL - CMD_GATEWAYINFO - set encryption level 1 (fallback) { error: { cause: undefined, message: 'Error: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key', context: undefined, stacktrace: 'Error: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key\n' + ' at module.exports.NodeRSA.$$decryptKey (/usr/src/app/node_modules/node-rsa/src/NodeRSA.js:301:19)\n' + ' at module.exports.NodeRSA.decrypt (/usr/src/app/node_modules/node-rsa/src/NodeRSA.js:249:21)\n' + ' at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:2002:47\n' + ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)' }, stationSN: 'T8170T1023411951', message: { seqNo: 0, channel: 255, commandType: 'CMD_GATEWAYINFO', signCode: 1, type: 0, dataType: 'CONTROL', data: 'REDACTED' }, key: 'REDACTED' }
> 
> I would really love to use this camera with my HomeAssistant installation if possible

I would verify the version that you are running... 1.8.0 has not been released yet from what I can see.

**Comment by wolfjank** [comment]
Hey there, do you already have any plans, when the release will come? 

Thank you. :-)
