### ISSUE TITLE
[Bug]: Eufy S350 VIDEO not working

### ISSUE THREAD

**Issue by danilichti** [bropat/eufy-security-ws#312]
### Version

 1.8.0

### Node version

1.8.0

### Operating System type

Linux

### Operating system version

Home Assistant 2024.3.0b6

### Describe the bug

After having added all add-ons and adding the "Eufy Security" device to HOAS, the camera device is detected but the video is stuck either in "IDLE" or "PREPARING". 

All other sensors are present and work. Pressing the "Start P2P Stream" changes nothing. 
 
![CleanShot 2024-03-05 at 15 52 48](https://github.com/bropat/eufy-security-ws/assets/73495201/f87aa1cd-3366-4de0-b54d-0d54262a8528)
![CleanShot 2024-03-05 at 15 52 58](https://github.com/bropat/eufy-security-ws/assets/73495201/53e2e5e0-91fb-44d1-a31e-fb56869a0165)

### To reproduce

2. Click on '...'

**Comment by danilichti** [comment]
```
Logger: homeassistant.components.camera
Quelle: components/camera/__init__.py:897
Integration: Kamera (Dokumentation, Probleme)
Erstmals aufgetreten: 15:47:21 (3 Vorkommnisse)
Zuletzt protokolliert: 15:47:44

Error requesting stream: camera.eufy_s350 does not support play stream service
```

**Comment by danilichti** [comment]
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024-03-05 14:34:52.992	INFO	eufy-security-ws	Eufy Security server listening on host 0.0.0.0, port 3000
2024-03-05 14:34:55.559	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onConnect] Connected to station T8416P0******** on host 192.168.8.134 and port *****
2024-03-05 14:34:57.924	INFO	eufy-security-ws:eufy-security-client	[main] Push notification connection successfully established
2024-03-05 14:37:46.692	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 37866 code: 1000 reason: Normal Closure
2024-03-05 14:38:53.650	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 37870 code: 1000 reason: Normal Closure
2024-03-05 14:39:03.334	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Stopping the station stream for the device T8416P002********, because we haven't received any data for 5000 seconds
2024-03-05 14:39:24.812	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Stopping the station stream for the device T8416P002********, because we haven't received any data for 5000 seconds
2024-03-05 14:39:34.881	ERROR	eufy-security-ws	Message error

 LivestreamNotRunningError  Livestream for device T8416P002******** could not be stopped, because it is not running, LivestreamNotRunningError
error stack:
  • message_handler.js	DeviceMessageHandler.handle
	/usr/src/app/node_modules/eufy-security-ws/dist/lib/device/message_handler.js:213
  • task_queues	process.processTicksAndRejections
	internal/process/task_queues:95
  • server.js	async Client.receiveMessage
	/usr/src/app/node_modules/eufy-security-ws/dist/lib/server.js:94
2024-03-05 14:39:41.584	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Stopping the station stream for the device T8416P002********, because we haven't received any data for 5000 seconds
2024-03-05 14:43:58.200	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 60536 code: 1000 reason: Normal Closure
2024-03-05 14:44:15.099	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 39546 code: 1000 reason: Normal Closure
2024-03-05 14:44:28.061	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Stopping the station stream for the device T8416P002********, because we haven't received any data for 5000 seconds
2024-03-05 14:44:42.336	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Stopping the station stream for the device T8416P002********, because we haven't received any data for 5000 seconds
2024-03-05 14:44:52.023	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 55214 code: 1006 reason: Abnormal Closure
2024-03-05 14:44:52.025	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 55238 code: 1006 reason: Abnormal Closure
2024-03-05 14:44:52.025	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 55230 code: 1006 reason: Abnormal Closure
2024-03-05 14:44:52.025	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 39534 code: 1006 reason: Abnormal Closure
2024-03-05 14:46:42.077	ERROR	eufy-security-ws:eufy-security-client	[main] Station rtsp url error {
  error: {
    cause: undefined,
    message: 'InvalidPropertyError: Property name is not valid',
    context: {
      name: 'rtspStreamUrl'
    },
    stacktrace: 'InvalidPropertyError: Property name is not valid\n' +
      '    at IndoorCamera.getPropertyMetadata (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:855:15)\n' +
      '    at IndoorCamera.setCustomPropertyValue (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:978:31)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:1997:20\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
  },
  stationSN: 'T8416P002********,
  channel: 0,
  url: 'rtsp://***********:Xu4JTyKaQ7Xx@192.168.8.134/live0'
}
2024-03-05 14:52:43.635	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 37182 code: 1000 reason: Normal Closure
2024-03-05 14:57:41.554	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Stopping the station stream for the device T8416P002*******, because we haven't received any data for 5000 seconds
```

**Comment by thilek** [comment]
How did you even get that many sensors working ? i don't even see that many.
<img width="677" alt="Screenshot at Mar 06 10-52-54" src="https://github.com/bropat/eufy-security-ws/assets/1127653/e8e5f852-5248-4dc0-8664-8789501867bf">

**Comment by danilichti** [comment]
> How did you even get that many sensors working ? i don't even see that many. <img alt="Screenshot at Mar 06 10-52-54" width="677" src="https://private-user-images.githubusercontent.com/1127653/310448107-e8e5f852-5248-4dc0-8664-8789501867bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjEwMDQsIm5iZiI6MTcwOTcyMDcwNCwicGF0aCI6Ii8xMTI3NjUzLzMxMDQ0ODEwNy1lOGU1Zjg1Mi01MjQ4LTRkYzAtODY2NC04Nzg5NTAxODY3YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTAyNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk2YjgxZGIwMTg3MjI2OTMzYzk3YzA3N2UzM2U1ZmU0YTNkMjY0NWIxYTE4OGU1NTZhZGNjNjE1ZWQwYTYwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3fVRyHYqVSTUHSCsAHpMPwc1SaDNtMlIjG6Jxwdo3lU">

They were all added automatically when I first setup the camera.

**Comment by thilek** [comment]
@danilichti  did you you use docker-compose ? since version 1.8.0 is not available in docker hub. So it's picking up older version for me.

**Comment by danilichti** [comment]
@thilek Home Assistant
