### ISSUE TITLE
Was working great yesterday... now error during start up.

### ISSUE THREAD

**Issue by TaZZaT** [bropat/eufy-security-ws#34]
**Describe the bug**  
when I run "src/bin/server.ts --config ./config.json"

get the following error:
(node:2519) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/opt/eufy-security-ws/src/bin/server.ts:3
import { resolve } from "path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**To Reproduce**  
1. src/bin/server.ts --config ./config.json

**Expected behavior**  
Program should start

**Screenshots & Logfiles**  
see errors above

**Versions:**  
 - Client version: latest
 - Node version: v12.22.7
 - Operating system: raspian

**Additional context**  
Worked great yesterday.  Awesome work.  This morning... it won't startup.

**Comment by bropat** [comment]
Have a look at the readme example. It must be started with ts-node. You started it with node...
