### ISSUE TITLE
[Bug]:  Indoor dual cam s350 - device.start_livestream failed.

### ISSUE THREAD

**Issue by Birdack** [bropat/eufy-security-ws#348]
### Version

1.8.0

### Node version

node:20-alpine 

### Operating System type

Linux

### Operating system version

yoctoLinux using docker arm64 images

### Describe the bug

Many of the commands directed to the camera function correctly. The error occurs when I attempt to initiate a start_livestream command. After 5 seconds, it responds with a stop streaming:

`2024-07-17 07:11:06.589	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Stopping the station stream for the device T8416XXXXXXXXXX, because we haven't received any data for 5000 seconds`

### To reproduce

after connection messages from client:
device.start_livestream T8416XXXXXXXXXX
wait 5000 ms

result:

```
eufy-security> 
{
  type: 'result',
  success: true,
  messageId: 'start_livestream',
  result: { async: true }
}
eufy-security> 
{
  type: 'event',
  event: {
    source: 'device',
    event: 'command result',
    serialNumber: 'T8416P0023434385',
    command: 'start_livestream',
    returnCode: 0,
    returnCodeName: 'ERROR_PPCS_SUCCESSFUL',
    customData: { command: { name: 'deviceStartLivestream', value: 0 } }
  }
}
eufy-security> 
{
  type: 'event',
  event: {
    source: 'device',
    event: 'command result',
    serialNumber: 'T8416P0023434385',
    command: 'stop_livestream',
    returnCode: 0,
    returnCodeName: 'ERROR_PPCS_SUCCESSFUL',
    customData: { command: { name: 'deviceStopLivestream' } }
  }
}
```

### Screenshots & Logfiles

Enabling debug on server side (env DEBUG=1 on docker):
```

2024-07-17 07:11:01.542	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol._sendCommand] Sending p2p command... {
  station: 'T8416XXXXXXXXXX',
  sequence: 3,
  commandType: 1350,
  channel: 0,
  retries: 0,
  messageStatesSize: 1
}
2024-07-17 07:11:01.561	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA DATA - Processing sequence 2... {
  stationSN: 'T8416XXXXXXXXXX',
  remoteAddress: '192.168.8.10',
  remotePort: 29254,
  dataType: 'DATA',
  seqNo: 2
}
2024-07-17 07:11:01.566	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleData] Handle DATA DATA - Decrypt Error {
  error: {
    cause: undefined,
    message: 'Error: error:1C80006B:Provider routines::wrong final block length',
    context: undefined,
    stacktrace: 'Error: error:1C80006B:Provider routines::wrong final block length\n' +
      '    at Decipheriv.final (node:internal/crypto/cipher:193:29)\n' +
      '    at decryptP2PData (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:102:18)\n' +
      '    at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1175:71)\n' +
      '    at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1152:26)\n' +
      '    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:986:26)\n' +
      '    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:118:56)\n' +
      '    at Socket.emit (node:events:518:28)\n' +
      '    at Socket.emit (node:domain:488:12)\n' +
      '    at UDP.onMessage [as onmessage] (node:dgram:941:8)'
  },
  stationSN: 'T8416XXXXXXXXXX',
  message: {
    seqNo: 2,
    channel: 0,
    commandType: 'CMD_SET_PAYLOAD',
    signCode: 1,
    type: 1,
    dataType: 'DATA',
    data: '000000000000000000000000000000000000000000000000000000000000000000000000'
  }
}
2024-07-17 07:11:01.568	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleData] Handle DATA DATA - Received data {
  stationSN: 'T8416XXXXXXXXXX',
  seqNo: 2,
  commandIdName: 'CMD_SET_PAYLOAD',
  commandId: 1350,
  resultCodeName: 'ERROR_PPCS_SUCCESSFUL',
  resultCode: 0,
  resultData: '0000000000000000000000000000000000000000000000000000000000000000',
  data: '000000000000000000000000000000000000000000000000000000000000000000000000',
  seqNumber: 4,
  p2pDataSeqNumber: 3,
  offsetDataSeqNumber: 0
}
```

**Comment by mst** [comment]
This probably the same as https://github.com/bropat/eufy-security-ws/issues/343

**Comment by Birdack** [comment]
I can give you access to the room via the internet, but not before Monday the 26th. Please provide the EU address to invite.

**Comment by bropat** [comment]
@Birdack 

patrick.broetto+eu1@gmail.com

**Comment by Birdack** [comment]
I've sent you an invite to control my device

**Comment by bropat** [comment]
@Birdack

Thank you for sharing the device.
Everything will be supported correctly in the next version.
I have already removed the shared device on my side.
