### ISSUE TITLE
[Question]: Anybody all of a sudden getting an API error?

### ISSUE THREAD

**Issue by verwirrrung** [bropat/eufy-security-ws#353]
### Ask your question

I updated HACS to the latest 2.0.0 several days ago and I just noticed yesterday that my Eufy smart lock and doorbell became unavailable, and they have been working for the longest time. I tried troubleshooting up to the point of reinstalling bropat's add-on and fuatakgun's integration and the common thing I noticed of all my troubleshooting is the error message below from the add-on log. Anybody having the same issue?

```
    message: 'ApiRequestError: API request error',
    context: {
      method: 'post',
      endpoint: 'v2/passport/login_sec',
      responseType: undefined,
      token: null,
      data: {
        ab: 'US',
        client_secret_info: {
          public_key: 'PUBLIC KEY REDACTED'},
        enc: 0,
        email: 'EMAIL REDACTED',
        password: '[***]',
        time_zone: -14400000,
        transaction: '1724598790223'
      }
    },
    stacktrace: 'ApiRequestError: API request error\n' +
      '    at HTTPApi.request (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:666:19)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async HTTPApi.login (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:324:34)\n' +
      '    at async EufySecurity.connect (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:798:9)\n' +
      '    at async DriverMessageHandler.handle (file:///usr/src/app/node_modules/eufy-security-ws/dist/lib/driver/message_handler.js:74:25)\n' +
      '    at async Client.receiveMessage (file:///usr/src/app/node_modules/eufy-security-ws/dist/lib/server.js:94:62)'
  }
}

```

**Comment by bropat** [comment]
No, everything works as expected on my side.
