### ISSUE TITLE
[Bug]: RangeError: Invalid key length

### ISSUE THREAD

**Issue by kvanbiesen** [bropat/eufy-security-ws#356]
### Version

1.9.0

### Node version

Node.js v20.15.1

### Operating System type

Other

### Operating system version

HAOS

### Describe the bug

When starting addon, and the first dive who connect to it, it makes the server crash

### To reproduce

Start plugin. Wait. crashes. Think its when a device connect to it.

### Screenshots & Logfiles

2024-08-27 18:39:53.373	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onConnect] Connected to station T8010P2322044049 on host 192.168.20.147 and port 14677
node:internal/crypto/cipher:121
    this[kHandle].initiv(cipher, credential, iv, authTagLength);
                  ^

RangeError: Invalid key length
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:121:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:140:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at createCipheriv (node:crypto:147:10)
    at encryptP2PData (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:90:48)
    at buildCommandWithStringTypePayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:298:48)
    at P2PClientProtocol._sendCommand (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:633:81)
    at P2PClientProtocol.sendQueuedMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:566:30)
    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:974:34)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:124:56) {
  code: 'ERR_CRYPTO_INVALID_KEYLEN'
}

**Comment by bropat** [comment]
@kvanbiesen 

I need more debug information (debug logs) to identify the problem.

**Comment by kvanbiesen** [comment]
darn, thought i added them.

Created some new one, hope this helps, currently rolled back to previous version

Sorry:/ 


[402f1039_eufy_security_ws_2024-09-15T10-48-24.780Z.log](https://github.com/user-attachments/files/17005456/402f1039_eufy_security_ws_2024-09-15T10-48-24.780Z.log)

**Comment by bropat** [comment]
> judging by the serial, i think its the eufy floodlight

Yes, it is:

```
2024-09-15 10:49:30.749	DEBUG	eufy-security-ws:eufy-security-client	[http] [Station.getCameraInfo] Station send get camera info command {
  stationSN: 'T8424N1021291061'
}
node:internal/crypto/cipher:121
    this[kHandle].initiv(cipher, credential, iv, authTagLength);
                  ^

RangeError: Invalid key length
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:121:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:140:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at createCipheriv (node:crypto:147:10)
    at encryptP2PData (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:90:48)
    at buildIntStringCommandPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:244:48)
    at P2PClientProtocol._sendCommand (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:623:76)
    at P2PClientProtocol.sendQueuedMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:566:30)
    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:974:34)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:124:56) {
  code: 'ERR_CRYPTO_INVALID_KEYLEN'
}
```

I think I have found the reason.

**Comment by kvanbiesen** [comment]
Nice. If you need access let me know or I can test it if needed

**Comment by bropat** [comment]
@kvanbiesen 

Can you share your device with me?

**Comment by bropat** [comment]
@kvanbiesen 

I cannot reproduce this error... :(

**Comment by kvanbiesen** [comment]
You still have rights.
To use the camera.The moment I upgrade from 1.8.x to 1.9. it crashes
indecently

**Comment by bropat** [comment]
@kvanbiesen 

What if you completely uninstall version 1.8.0 and then install version 1.9.0?

**Comment by kvanbiesen** [comment]
Same error. Country is BE. Everything is is default

**Comment by bropat** [comment]
@kvanbiesen 

Can you try version `1.9.1`?

**Comment by kvanbiesen** [comment]
yup, doesnt crash at startup. Seems to be fixed. have to test the rest of the deviced but i assume if it starts. They should be working


Thanks @bropat
