### ISSUE TITLE
[Bug]: Can't install 1.9.0

### ISSUE THREAD

**Issue by andersmoldin** [bropat/eufy-security-ws#357]
### Version

1.9.0

### Node version

1.0

### Operating System type

Other

### Operating system version

1.0

### Describe the bug

In Home Assistant, when I'm trying to update the eufy-security-ws add-on from version 1.8.0-2 to 1.9.0 I get an error:

Failed to perform the action update/install. Error updating eufy-security-ws: Can't install bropat/hassio-eufy-security-ws-armv7:1.9.0: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=1.9.0&fromImage=bropat%2Fhassio-eufy-security-ws-armv7&platform=linux%2Farm%2Fv7: Not Found ("manifest for bropat/hassio-eufy-security-ws-armv7:1.9.0 not found: manifest unknown: manifest unknown")

PS. Versions from Home Assistants About dialog:

Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1

### To reproduce

In Home Assistant,
1. Go to Settings, System, Updates, click eufy-security-ws Update and then Install.
2. See error

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/b4845f04-a0f7-4a34-a385-e2882771c42d)

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:19:14 (5 occurrences)
Last logged: 10:29:04

[2413169008] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 168, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 57, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 134, in async_update_addon
    return await hassio.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 599, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Can't install bropat/hassio-eufy-security-ws-armv7:1.9.0: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=1.9.0&fromImage=bropat%2Fhassio-eufy-security-ws-armv7&platform=linux%2Farm%2Fv7: Not Found ("manifest for bropat/hassio-eufy-security-ws-armv7:1.9.0 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 458, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 170, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating eufy-security-ws: Can't install bropat/hassio-eufy-security-ws-armv7:1.9.0: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=1.9.0&fromImage=bropat%2Fhassio-eufy-security-ws-armv7&platform=linux%2Farm%2Fv7: Not Found ("manifest for bropat/hassio-eufy-security-ws-armv7:1.9.0 not found: manifest unknown: manifest unknown")
```

**Comment by extremeshok** [comment]
Odroid XU4 + hassio latest
`
Failed to perform the action update/install. Error updating eufy-security-ws: Can't install bropat/hassio-eufy-security-ws-armv7:1.9.0: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=1.9.0&fromImage=bropat%2Fhassio-eufy-security-ws-armv7&platform=linux%2Farm%2Fv7: Not Found ("manifest for bropat/hassio-eufy-security-ws-armv7:1.9.0 not found: manifest unknown: manifest unknown")
`

**Comment by ablohm** [comment]
Same issue for me. Running on HASS OS 13.1, Core 2024.8.3, RPi4

**Comment by stevied65** [comment]
Same issue for me.

**Comment by nukleuz80** [comment]
Here is the same issue with latest HAOS 13.1 and Core 2024.8.3 on Proxmox.

**Comment by fuatakgun** [comment]
Publish to docker.hub did not happen for armv7 apparently.

https://hub.docker.com/r/bropat/hassio-eufy-security-ws-armv7

The latest release is 6 months old.

Publish action might have failed.

**Comment by nukleuz80** [comment]
After system restart i can install the update 1.9.0

**Comment by bropat** [comment]
When creating the container images for armhf and on armv7, there has been a problem for some time that causes the build process to hang and, as in this case, to be interrupted by GitHub Actions after 6 hours:

https://github.com/bropat/hassio-eufy-security-ws/actions/runs/10581969120

There are numerous issues about this problem, some possible workarounds but no definitive solution:

* [Docker build with GitHub Actions failed on multi arch with node:alpine](https://github.com/nodejs/docker-node/issues/1798)
* [NPM install stucks with node:20](https://github.com/nodejs/docker-node/issues/1946)
* [docker buildx hang on node:22-alpine (armv6/armv7)](https://github.com/nodejs/docker-node/issues/2077)
* [Docker build hangs for linux/arm/v7](https://github.com/docker/build-push-action/issues/1071)

I have a possible workaround in mind, but I need some time to test everything.

**Comment by bropat** [comment]
In the meantime, I have solved it manually:

* https://hub.docker.com/r/bropat/hassio-eufy-security-ws-armhf
* https://hub.docker.com/r/bropat/hassio-eufy-security-ws-armv7

Let me know if it works.

**Comment by extremeshok** [comment]
thanks for fixing

**Comment by bropat** [comment]
It's an issue with QEMU, so we'll wait until it's fixed there:

https://gitlab.com/qemu-project/qemu/-/issues/1729

**Comment by Clem-** [comment]
> In the meantime, I have solved it manually:
> 
>     * https://hub.docker.com/r/bropat/hassio-eufy-security-ws-armhf
> 
>     * https://hub.docker.com/r/bropat/hassio-eufy-security-ws-armv7
> 
> 
> Let me know if it works.

Hi, thanks for the fix!
Could you explain how you managed to build it? 
I would like to directly build `eufy-security-ws` for armv7 since I am not using hassio.
